# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f45af79c5a5c02dfa41fb9da9a8143bf3fe072e967d3efb94e2dc60c5483bf7bce94f68fd700450bcca9108a848dc88818d896172b38ed32485e2d36f1e7163d

test:
  secret_key_base: 46c45c899872b8044afd879144ad7984e694bbc508de08ed57d7360082a869600104237700b0946b88f5170be571155cd950ad21198222f8291a6aa3c9e8cd68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
